### ISSUE TITLE
Removing Keys from Parsed Objects

### ISSUE THREAD

**Issue by spyrosoft** [madnificent/jsown#12]
Thoughts on being able to remove keys from parsed objects in addition to adding them?

**Comment by madnificent** [comment]
It seems like something useful to have available indeed.  I've just added remkey on the devel branch.

```
(let ((o (jsown:new-js ("foo" "bar") ("baz" "bang") ("bing" "bong"))))
  (jsown:remkey o "baz")
  (princ (jsown:to-json o)))

> {"bing": "bong", "foo": "bar"}
```

Does that cover what you were looking for?  Any notes on different expectations of the functionality or implementation?

**Comment by spyrosoft** [comment]
Awesome. That's exactly what I was looking for. Thank you!

**Comment by madnificent** [comment]
Pushed to master.  Should be in the next QuickLisp release.
