### ISSUE TITLE
`jsown:parse` fails on even length strings on ECL

### ISSUE THREAD

**Issue by ralt** [madnificent/jsown#18]
A simple REPL session:

```
CL-USER> (jsown:parse "{\"f\": \"f\"}")
(:OBJ ("f" . "f"))
CL-USER> (jsown:parse "{\"f\": \"ff\"}")
; Evaluation aborted on #<a SIMPLE-TYPE-ERROR>.
CL-USER> 
```

The error message being this: `11 is not a valid index into the object "{\"f\": \"ff\"}"`.

I've narrowed it down to `SUBSEQ-UNTIL/UNESCAPE`'s loop:

```
    (loop do (incf (the fixnum unescape-count) (the fixnum (next-char/i buffer)))
       until (eql (current-char buffer) last-char))
```

In ECL, for some reason, `(next-char/i buffer)` is actually called _twice_ per iteration. This completely messes up the buffer's index, and obviously the `until` is missed, so it errors out with an out-of-bounds error.

This version works:

```
    (loop do (incf unescape-count (the fixnum (next-char/i buffer)))
       until (eql (current-char buffer) last-char))
```

Removing the `THE` around `unescape-count` removes this bug. It's easily reproducible:

```
CL-USER> (defparameter *foo* 1)
*FOO*
CL-USER> (defun foo ()
	   (incf *foo*))
FOO
CL-USER> (let ((foo 0))
	   (incf (the fixnum foo) (foo)))
3
CL-USER> *foo*
3
```

Anyway, I've reported this bug in ECL: https://gitlab.com/embeddable-common-lisp/ecl/issues/401

But maybe you want to do something too? I wasn't sure if you would accept a PR that would either remove the `THE` altogether, or only do that for ECL.

**Comment by madnificent** [comment]
Top quality issue report @ralt.  Very nice to receive.

Assuming this is an ECL-only issue, I would prefer an ECL-specific code-path to be added for the time being.  I don't know how proactive ECL users are, but I would suspect it to take quite some time before everyone is on an improved version.

You can make a PR for the ECL-specific support if you'd like.  If not, I can build a commit based on your excellent write-up.

**Comment by ralt** [comment]
Hey,

Thanks for answering so quickly!

I don't really care about writing the PR, please go ahead with it, that will be less hassle for everyone involved. (Reviewing, merging, etc.)

Cheers
