### ISSUE TITLE
Avoid bare (declaim (optimize ...))

### ISSUE THREAD

**Issue by jcornez** [madnificent/jsown#20]
At the top of the reader.lisp and writer.lisp files, please add the `eval-when` as follows.  If not, the optimization settings can be pervasive, and not local to the file compilation, as they ought to be.
```cl
(eval-when (:compile-toplevel)
  (declaim (optimize (speed 3) (safety 0) (debug 0))))
```

**Comment by madnificent** [comment]
Thank you for this very useful input.  I will push the change.  Can you point me to the relevant portion of the spec?

**Comment by jcornez** [comment]
https://franz.com/support/documentation/current/ansicl/dictentr/declaim.htm

>  As with other defining macros, it is unspecified whether or not the compile-time side-effects of a declaim persist after the file has been compiled.

**Comment by madnificent** [comment]
Thank you for the clear issue.
