### ISSUE TITLE
`to-json` of improper lists

### ISSUE THREAD

**Issue by GPPassos** [madnificent/jsown#21]
Although `to-json ((list list))` works fine for [proper lists](http://clhs.lisp.se/Body/26_glo_p.htm#proper_list), they do not for other, improper lists such as a simple cons `(a . b)` (an example of a [dotted list](http://clhs.lisp.se/Body/26_glo_d.htm#dotted_list)), raising an error.

This creates issues in using `to-json` of association lists, such as `((a . 1) (b . 2))`.

Thanks.

**Comment by madnificent** [comment]
Hi @GPPassos.  I'm assuming you're discussing the internal format which jsown uses to store json content.  This format should be considered an internal format, hence not all structures will be supported and the format may change over time (though in practice, it doesn't).

Although lists convert nicely into json arrays (which is to be expected, I suppose), some other primitive values are constructed using specific language constructs.  For example, we use `:false` in lisp to denote json's `false` as lisp doesn't make the distinction between an empty list and false.  As such, some other structures should be converted using the primitives in accessors.lisp.  If you intend to write content (like association lists), you'll want to convert them using this higher-level stable logic.

Does this clarify the reasoning that was followed in the library so far?

**Comment by madnificent** [comment]
Hi @GPPassos.  I strongly suspect you found your way and moved on.  So this is mainly for archeologists.

The general idea is that you construct objects using the functions offered by jsown.  So content you receive by doing `jsown:parse` or by updating an object received through `jsown:new-js` should work, but most other Lisp structures would likely not.  If I recall correctly, lists are the exception here.

I'm closing this issue but feel free to ping me back if you'd still need more info.
